### ISSUE TITLE
convertFile throws org.apache.xml.dtm.DTMConfigurationException exception

### ISSUE THREAD

**Issue by brztss** [asciidoctor/asciidoctorj-epub3#17]
Hello. I have encountered a problem with converting any .adoc file to .epub file. Execution takes a few seconds and then following exception is thrown
```
Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.RuntimeException: org.apache.xml.dtm.DTMConfigurationException: No default implementation found] with root cause
java.lang.ClassNotFoundException: nokogiri.internals.XalanDTMManagerPatch
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[na:na]
	at org.apache.xml.dtm.ObjectFactory.findProviderClass(ObjectFactory.java:513) ~[mn2pdf-1.48.jar:1.48]
	at org.apache.xml.dtm.ObjectFactory.lookUpFactoryClass(ObjectFactory.java:219) ~[mn2pdf-1.48.jar:1.48]
	at org.apache.xml.dtm.ObjectFactory.createObject(ObjectFactory.java:133) ~[mn2pdf-1.48.jar:1.48]
	at org.apache.xml.dtm.ObjectFactory.createObject(ObjectFactory.java:103) ~[mn2pdf-1.48.jar:1.48]
	at org.apache.xml.dtm.DTMManager.newInstance(DTMManager.java:137) ~[mn2pdf-1.48.jar:1.48]
	at org.apache.xpath.XPathContext.<init>(XPathContext.java:102) ~[mn2pdf-1.48.jar:1.48]
	at org.apache.xpath.XPathContext.<init>(XPathContext.java:349) ~[mn2pdf-1.48.jar:1.48]
	at nokogiri.XmlXpathContext.newXPathContext(XmlXpathContext.java:253) ~[na:na]
	at nokogiri.XmlXpathContext.getXPathContext(XmlXpathContext.java:227) ~[na:na]
	at nokogiri.XmlXpathContext.tryGetNodeSet(XmlXpathContext.java:202) ~[na:na]
	at nokogiri.XmlXpathContext.node_set(XmlXpathContext.java:179) ~[na:na]
	at nokogiri.XmlXpathContext.evaluate(XmlXpathContext.java:139) ~[na:na]
	at nokogiri.XmlXpathContext$INVOKER$i$evaluate.call(XmlXpathContext$INVOKER$i$evaluate.gen) ~[na:na]
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:393) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:206) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:325) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:128) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:115) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:329) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:87) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.ir.instructions.CallBase.interpret(CallBase.java:549) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:361) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:128) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:115) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:329) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:87) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.ir.instructions.CallBase.interpret(CallBase.java:549) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:361) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:86) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:201) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:188) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:206) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:372) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:175) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:316) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:80) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:164) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:151) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:198) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:351) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:144) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:345) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:86) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:201) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:188) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:206) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:372) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:175) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:316) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:86) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:201) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:188) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:206) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:372) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:175) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:316) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:86) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:201) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:188) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:206) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:372) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:175) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:316) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:86) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:201) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:188) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.RubyClass.finvokeWithRefinements(RubyClass.java:528) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.RubyBasicObject.send(RubyBasicObject.java:1716) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.RubyKernel.send(RubyKernel.java:2235) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.RubyKernel$INVOKER$s$send.call(RubyKernel$INVOKER$s$send.gen) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodOneOrTwoOrNBlock.call(JavaMethod.java:444) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:393) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:206) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:325) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:92) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:238) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:225) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:214) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:393) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:206) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:325) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:86) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:201) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:188) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:206) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:372) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:175) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:316) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:92) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:238) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:225) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:214) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:393) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:206) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:325) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:116) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.runtime.MixedModeIRBlockBody.commonYieldPath(MixedModeIRBlockBody.java:136) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.runtime.IRBlockBody.doYield(IRBlockBody.java:170) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.runtime.BlockBody.yield(BlockBody.java:108) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.runtime.Block.yield(Block.java:188) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.RubyIO.ensureYieldClose(RubyIO.java:1154) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.RubyIO.open(RubyIO.java:1148) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.RubyIO$INVOKER$s$0$0$open.call(RubyIO$INVOKER$s$0$0$open.gen) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:329) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:87) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:94) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.ir.instructions.CallBase.interpret(CallBase.java:546) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:361) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:128) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:115) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:180) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.RubyClass.finvoke(RubyClass.java:782) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.runtime.Helpers.invoke(Helpers.java:661) ~[jruby-base-9.3.4.0.jar:na]
	at org.jruby.RubyBasicObject.callMethod(RubyBasicObject.java:370) ~[jruby-base-9.3.4.0.jar:na]
	at org.asciidoctor.jruby.internal.JRubyAsciidoctor.convertFile(JRubyAsciidoctor.java:392) ~[asciidoctorj-2.5.4.jar:2.5.4]
	at org.asciidoctor.jruby.internal.JRubyAsciidoctor.convertFile(JRubyAsciidoctor.java:416) ~[asciidoctorj-2.5.4.jar:2.5.4]
	at org.asciidoctor.jruby.internal.JRubyAsciidoctor.convertFile(JRubyAsciidoctor.java:411) ~[asciidoctorj-2.5.4.jar:2.5.4]
```

However when I'm converting my .adoc file using asciidoc-epub3 Ruby gem it works perfectly fine.
The code which I've created is following
```
        try (Asciidoctor asciidoctor = Asciidoctor.Factory.create()) {
            File fileToConvert = new ClassPathResource("spine.adoc").getFile();
            File convertedFile = new File("converted");
            Options convertingOptions =
                    Options.builder().safe(SafeMode.SAFE).toFile(convertedFile).backend("epub3").build();
            asciidoctor.convertFile(fileToConvert, convertingOptions);
            log.warn(Files.readString(convertedFile.toPath()));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
```
Is it AsciidoctorJ bug or probably problem related with my application?

**Comment by robertpanzer** [comment]
Could you please provide a project that reproduces that error?

**Comment by robertpanzer** [comment]
Since the error message contains sth about `Servlet.service`, are you possibly running this inside of a Spring Boot app?
In that case could you check this https://docs.asciidoctor.org/asciidoctorj/latest/guides/run-with-springboot/ and add `**/nokogiri.jar` to the list?

**Comment by brztss** [comment]
Thank you for your reply. Yes, it is Spring Boot app. Unfortunately I can't provide the project. However I have detected that existence of another library on my classpath (which is loaded not from repository, but system path) together with asciidoctorJ-epub3 causes this problem. This library is `mnconvert` and it uses asciidoctor gem underneath. Adding `-Dorg.apache.xml.dtm.DTMManager=org.apache.xml.dtm.ref.DTMManagerDefault` to JVM options solved this problem, but I'm not quite sure whether it is safe solution.  
I have checked running with spring-boot article. I'm using Maven, so could you please tell me how should I add `**/nokogiri.jar` in this particular case?

**Comment by robertpanzer** [comment]
I guess you'll need to apply the repackage goal: https://docs.spring.io/spring-boot/docs/current/maven-plugin/reference/htmlsingle/#goals-repackage-parameters-details-requiresUnpack
I am not sure how to configure this so that this jar will be on the classpath.
